### ISSUE TITLE
Confusion over schema version

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [postmanlabs/schemas#119]
Checking through the json generated from Postman, I saw that it has the schema url at https://schema.getpostman.com/json/collection/v2.1.0/collection.json which is a v4 schema. The README itself mentions that they conform to v4 schema. But when I visit the website at https://schema.getpostman.com/ and click the link to the schema, I get a v7 schema. I checked the generated collection json with both v4 and v7 and it passes for both the versions (at least for my collection). As such I am a bit confused as to which version of json-schema is actually implemented for the schema. Any light on this is highly appreciated.

**Comment by codenirvana** [comment]
@SayakMukhopadhyay Website by default points to draft-07 but you can access both the versions using the following links:
- https://schema.getpostman.com/collection/json/v2.1.0/draft-07/collection.json
- https://schema.getpostman.com/collection/json/v2.1.0/draft-04/collection.json

The schema URL in the exported collection is supported for backward compatibility (draft-04).

**Comment by SayakMukhopadhyay** [comment]
Thanks for the reply. Just to clarify, is it safe to assume that all exported collection json will be valid with draft-07 schema?

**Comment by codenirvana** [comment]
@SayakMukhopadhyay Yes 😄
