### ISSUE TITLE
Collections V2 is invalid

### ISSUE THREAD

**Issue by t-botz** [postmanlabs/schemas#12]
https://github.com/postmanlabs/schemas/blob/develop/json/collection/v2.0.0/index.json#L856
The above line is invalid according to the json schema specs.
You can easily test your schema here : 
http://www.jsonschemavalidator.net/

**Comment by kunagpal** [comment]
Duplicate of #13

**Comment by t-botz** [comment]
@kunagpal how is that a duplicate?? One is about the schema itself, this one is about the data generated.... That's two very different problems with two very different resolution...

**Comment by jvkaam** [comment]
+1

**Comment by kunagpal** [comment]
@jvkaam @thibaultdelor This issue has been fixed, feel free to revert if you're facing other difficulties 😄
