### ISSUE TITLE
Postman client spit out invalid collection according to the schemas

### ISSUE THREAD

**Issue by t-botz** [postmanlabs/schemas#13]
If you export the postman echo collection from the postman client, it violate the schema in multiple ways.
For example it violates the fact that, in the version 2.0.0 of the spec,  items are not allowed to have a name.

Whatever the client export doesn't respect any of your schemas which makes those schemas absolutely useless IMO...

**Comment by kunagpal** [comment]
@thibaultdelor This issue has been fixed, thanks for letting us know 😄
