### ISSUE TITLE
Certificate's `matches` should use `items`

### ISSUE THREAD

**Issue by stabacco** [postmanlabs/schemas#156]
Since the `matches` field is an array i believe it should declare its child  as `items` instead of `item`. 
See below:

https://github.com/postmanlabs/schemas/blob/e6429ead7a805985e68f9e1fe49ec5a4c5234d5a/schemas/draft-07/v2.1.0/collection/certificate.json#L11-L14

**Comment by jmini** [comment]
I agree with @stabacco :

In the [JSON Shema](https://json-schema.org/) specification, inside a schema with type `"array"`, the attribute is called `"items"` and not `"item"`.

See [array reference](https://json-schema.org/understanding-json-schema/reference/array.html) for JSON Schema draft 7.
It is the same for the`draft-04` json schema: [JSON Schema draft-4 core definitions](https://tools.ietf.org/html/draft-zyp-json-schema-04).

**Comment by codenirvana** [comment]
Right, looks like we missed a test (examples) for certificate schema. 🤦
