### ISSUE TITLE
Allow `request.tests` to permit "incomplete" tests

### ISSUE THREAD

**Issue by sethbattin** [postmanlabs/schemas#8]
It would be useful to be able to mark tests incomplete, similar to: https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html.  Such tests would not cause a "fail" result for a test collection, but they would be highlighted for future attention.  In Postman or Newman's case, this could be a yellow icon or a CLI warning message, respectively.

The use case is for continuous integration, when adding tests to features that have preexisting invalid behavior (for example, the incorrect response code).  A failure result is not useful, because it obscures new "real" failures for incoming changes.  A passing test is also not useful, because it tests invalid results and provide no indication of a problem.

Obviously this is more than a schema change; I can make a similar feature request wherever is appropriate for Newman.

**Comment by shamasis** [comment]
It's a great idea. I think the first step to that would be a formal test suite library in the scripts. Something like mocha. That could then have things marked as ".skip". 

This is ideally a feature request for the project "postman-app-support". :-)

**Comment by sethbattin** [comment]
There it is:  https://github.com/postmanlabs/postman-app-support/issues/1693

**Comment by kunagpal** [comment]
@sethbattin This is now possible with the all new pm API, like so:
```js
pm.test.skip('This test will not be run', function () {
  pm.expect(4).to.equal(4);
})
```

More details here: https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
